export const resList = [
  {
    id: 1,
    name: "The Food House",
    cuisine: ["Indian", "Chinese"],
    rating: 4.5,
    deliveryTime: "30 mins",
    image: "https://source.unsplash.com/400x300/?food",
  },
  {
    id: 2,
    name: "Burger Hub",
    cuisine: ["American", "Fast Food"],
    rating: 4.2,
    deliveryTime: "25 mins",
    image: "https://source.unsplash.com/400x300/?burger",
  },
  {
    id: 3,
    name: "Pizza Paradise",
    cuisine: ["Italian", "Pizza"],
    rating: 4.7,
    deliveryTime: "40 mins",
    image: "https://source.unsplash.com/400x300/?pizza",
  },
  {
    id: 4,
    name: "Tandoori Treats",
    cuisine: ["Indian", "Mughlai"],
    rating: 4.6,
    deliveryTime: "35 mins",
    image: "https://source.unsplash.com/400x300/?tandoori",
  },
  {
    id: 5,
    name: "Sushi Delight",
    cuisine: ["Japanese", "Sushi"],
    rating: 4.8,
    deliveryTime: "45 mins",
    image: "https://source.unsplash.com/400x300/?sushi",
  },
  {
    id: 6,
    name: "Taco Fiesta",
    cuisine: ["Mexican", "Tacos"],
    rating: 4.3,
    deliveryTime: "20 mins",
    image: "https://source.unsplash.com/400x300/?tacos",
  },
  {
    id: 7,
    name: "Healthy Bites",
    cuisine: ["Salads", "Healthy"],
    rating: 4.5,
    deliveryTime: "30 mins",
    image: "https://source.unsplash.com/400x300/?salad",
  },
  {
    id: 8,
    name: "Biryani Bliss",
    cuisine: ["Indian", "Biryani"],
    rating: 4.9,
    deliveryTime: "50 mins",
    image: "https://source.unsplash.com/400x300/?biryani",
  },
  {
    id: 9,
    name: "Pasta Heaven",
    cuisine: ["Italian", "Pasta"],
    rating: 4.4,
    deliveryTime: "28 mins",
    image: "https://source.unsplash.com/400x300/?pasta",
  },
  {
    id: 10,
    name: "Kebab Kingdom",
    cuisine: ["Middle Eastern", "Kebabs"],
    rating: 4.7,
    deliveryTime: "38 mins",
    image: "https://source.unsplash.com/400x300/?kebab",
  },
  {
    id: 11,
    name: "Dessert Haven",
    cuisine: ["Desserts", "Bakery"],
    rating: 4.6,
    deliveryTime: "15 mins",
    image: "https://source.unsplash.com/400x300/?dessert",
  },
  {
    id: 12,
    name: "BBQ Express",
    cuisine: ["American", "BBQ"],
    rating: 4.3,
    deliveryTime: "40 mins",
    image: "https://source.unsplash.com/400x300/?bbq",
  },
  {
    id: 13,
    name: "Wok & Roll",
    cuisine: ["Chinese", "Thai"],
    rating: 4.2,
    deliveryTime: "35 mins",
    image: "https://source.unsplash.com/400x300/?chinesefood",
  },
  {
    id: 14,
    name: "Vegan Vibes",
    cuisine: ["Vegan", "Healthy"],
    rating: 4.9,
    deliveryTime: "32 mins",
    image: "https://source.unsplash.com/400x300/?vegan",
  },
  {
    id: 15,
    name: "Seafood Shack",
    cuisine: ["Seafood", "Grill"],
    rating: 4.8,
    deliveryTime: "50 mins",
    image: "https://source.unsplash.com/400x300/?seafood",
  },
];
